# Generated by Django 4.0.4 on 2022-04-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='title',
            new_name='position',
        ),
    ]
